In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('/content/bike.csv')
df.head()

Gender  Age  Salary  Purchase Duke
0    Male   19   19000              0
1    Male   35   20000              0
2  Female   26   43000              0
3  Female   27   57000              0
4    Male   19   76000              0

In [8]:
x = df.drop(['Purchase Duke'], axis=1)
y = df['Purchase Duke']

In [9]:
x.shape


(400, 3)

In [10]:
y.shape

(400,)

In [11]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
x["Gender"] = label_encoder.fit_transform(x["Gender"])

In [12]:
x.shape

(400, 3)

In [13]:
x

Gender  Age  Salary
0         1   19   19000
1         1   35   20000
2         0   26   43000
3         0   27   57000
4         1   19   76000
..      ...  ...     ...
395       0   46   41000
396       1   51   23000
397       0   50   20000
398       1   36   33000
399       0   49   36000

[400 rows x 3 columns]

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [15]:
from sklearn.svm import SVC

svcclassifier = SVC(kernel='linear', random_state =1)
svcclassifier.fit(x_train, y_train)
y_pred = svcclassifier.predict(x_test)

In [16]:
from sklearn import metrics
print(metrics.accuracy_score(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))


0.85
[[48  4]
 [ 8 20]]


In [17]:
conf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(conf_matrix)
TP = conf_matrix[0][0]
TN = conf_matrix[1][1]
FN = conf_matrix[1][0]
FP = conf_matrix[0][1]

[[48  4]
 [ 8 20]]


In [18]:
from sklearn.svm import SVC

svcclassifier = SVC(kernel='rbf', random_state =1)
svcclassifier.fit(x_train, y_train)
y_pred = svcclassifier.predict(x_test)

In [19]:
from sklearn import metrics
print(metrics.accuracy_score(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))


0.7375
[[49  3]
 [18 10]]


In [20]:
conf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(conf_matrix)
TP = conf_matrix[0][0]
TN = conf_matrix[1][1]
FN = conf_matrix[1][0]
FP = conf_matrix[0][1]

[[49  3]
 [18 10]]
