In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
import pandas as pd
docs = pd.read_table("/content/SMSSpamCollection", header=None, names=["class","sns"])
docs.head(10)

class                                                sns
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [ ]:
ham_spam = docs['class'].value_counts()
print(ham_spam)


class
ham     4825
spam     747
Name: count, dtype: int64


In [ ]:
docs['label'] = docs['class'].map({'ham':0, 'spam':1})
docs.head()

class                                                sns  label
0   ham  Go until jurong point, crazy.. Available only ...      0
1   ham                      Ok lar... Joking wif u oni...      0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...      1
3   ham  U dun say so early hor... U c already then say...      0
4   ham  Nah I don't think he goes to usf, he lives aro...      0

In [ ]:
x = docs['sns']
y = docs['label']
print(x.shape)
print(y.shape)

(5572,)
(5572,)


In [ ]:
x.head()

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: sns, dtype: object

In [ ]:
y.head()

0    0
1    0
2    1
3    0
4    0
Name: label, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

x_train.head()


1978    Reply to win £100 weekly! Where will the 2006 ...
3989    Hello. Sort of out in town already. That . So ...
3935     How come guoyang go n tell her? Then u told her?
4078    Hey sathya till now we dint meet not even a si...
4086    Orange brings you ringtones from all time Char...
Name: sns, dtype: object

In [ ]:
y_train.head()

1978    1
3989    0
3935    0
4078    0
4086    1
Name: label, dtype: int64

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer(stop_words='english')

In [ ]:
vect.fit(x_train)


CountVectorizer(stop_words='english')

In [ ]:
vect.vocabulary_

{'squeeeeeze': 2731,
 'christmas': 756,
 'hug': 1550,
 'lik': 1775,
 'frndshp': 1314,
 'den': 964,
 'cute': 902,
 'luvd': 1846,
 'lucky': 1841,
 'people': 2203,
 'hate': 1462,
 've': 3111,
 'sorta': 2697,
 'blown': 579,
 'couple': 858,
 'times': 2951,
 'recently': 2410,
 'id': 1570,
 'text': 2903,
 'blue': 580,
 'looking': 1813,
 'weed': 3190,
 'mmm': 1957,
 'thats': 2912,
 'better': 545,
 'got': 1388,
 'roast': 2488,
 'drinks': 1053,
 'good': 1382,
 'indian': 1604,
 'mm': 1956,
 'kanji': 1683,
 'dont': 1037,
 'eat': 1084,
 'heavy': 1482,
 'ok': 2129,
 'ring': 2480,
 'comes': 798,
 'guys': 1426,
 'costumes': 854,
 'gift': 1361,
 'future': 1327,
 'yowifes': 3317,
 'hint': 1503,
 'sary': 2534,
 'just': 1678,
 'need': 2043,
 'tim': 2949,
 'bollox': 584,
 'hurt': 1558,
 'lot': 1820,
 'tol': 2972,
 'love': 1827,
 'isn': 1634,
 'decision': 947,
 'feeling': 1225,
 'decide': 944,
 'life': 1770,
 'simpler': 2643,
 'magical': 1865,
 'supervisor': 2827,
 'lor': 1815,
 'thk': 2929,
 'students': 27

In [ ]:
vect.fit(x_test)

CountVectorizer(stop_words='english')

In [ ]:
x_train_dtm = vect.transform(x_train)
x_train_dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 26546 stored elements and shape (4457, 3325)>

In [ ]:
x_train_transformed = vect.transform(x_train)
x_test_transformed = vect.transform(x_test)


In [ ]:
x_test_transformed

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8723 stored elements and shape (1115, 3325)>

In [ ]:
print(x_train_transformed)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 26546 stored elements and shape (4457, 3325)>
  Coords	Values
  (0, 91)	1
  (0, 894)	1
  (0, 1109)	1
  (0, 2450)	1
  (0, 2581)	1
  (0, 2593)	1
  (0, 2768)	1
  (0, 3195)	1
  (0, 3224)	1
  (0, 3259)	1
  (1, 1037)	1
  (1, 1488)	1
  (1, 1520)	1
  (1, 1709)	1
  (1, 1758)	1
  (1, 2696)	1
  (1, 2994)	1
  (2, 797)	1
  (2, 2888)	1
  (2, 2973)	1
  (3, 996)	1
  (3, 1494)	1
  (3, 1914)	1
  (3, 2542)	1
  (3, 2648)	1
  :	:
  (4451, 1821)	2
  (4451, 2450)	2
  (4451, 2768)	1
  (4451, 2774)	1
  (4451, 3040)	1
  (4451, 3224)	1
  (4452, 979)	1
  (4452, 1085)	1
  (4452, 1388)	1
  (4452, 1497)	1
  (4452, 3246)	1
  (4453, 1731)	1
  (4453, 1794)	1
  (4453, 2695)	1
  (4454, 1310)	1
  (4454, 1481)	1
  (4455, 1665)	1
  (4455, 2099)	1
  (4455, 2592)	1
  (4455, 2973)	1
  (4456, 979)	1
  (4456, 1678)	1
  (4456, 2543)	1
  (4456, 2690)	1
  (4456, 2865)	1


In [ ]:
from  sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()

In [ ]:
naive_model = mnb.fit(x_train_transformed, y_train)

In [ ]:
y_pred_class =mnb.predict(x_test_transformed)

In [ ]:
print(y_pred_class)

[0 0 0 ... 0 0 0]


In [ ]:
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.9730941704035875

In [ ]:
y_pred_class

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
metrics.confusion_matrix(y_test, y_pred_class)

array([[940,  26],
       [  4, 145]])

In [ ]:
confusion = metrics.confusion_matrix(y_test, y_pred_class)
print(confusion)

[[940  26]
 [  4 145]]


In [ ]:
confusion = metrics.confusion_matrix(y_test, y_pred_class)

TN, FP, FN, TP = confusion.ravel()

sensitivity = TP / float(FN + TP)
specificity = TN / float(TN + FP)

print("Sensitivity:", sensitivity)
print("Specificity:", specificity)


Sensitivity: 0.9731543624161074
Specificity: 0.9730848861283644


In [ ]:
precision = TP / float(TP + FP)
print("Precision:", precision)
print(metrics.precision_score(y_test, y_pred_class))

Precision: 0.847953216374269
0.847953216374269


In [ ]:
print("precision",precision)
print("PRECISION SCORE:" ,  metrics.precision_score(y_test, y_pred_class))
print("RECALL SCORE:" , metrics.recall_score(y_test, y_pred_class))
print("F1 SCORE:" , metrics.f1_score(y_test, y_pred_class))

precision 0.847953216374269
PRECISION SCORE: 0.847953216374269
RECALL SCORE: 0.9731543624161074
F1 SCORE: 0.90625


In [ ]:
import joblib
fin_model = naive_model


In [81]:
import os
import joblib

output_dir = "/content/ML_7"   # Save directly under /content instead
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

joblib.dump(fin_model, os.path.join(output_dir, "spam_ham_model.pkl"))
joblib.dump(vect, os.path.join(output_dir, "spam_ham_vectorizer.pkl"))

print("✅ Model and vectorizer saved successfully in:", output_dir)


✅ Model and vectorizer saved successfully in: /content/ML_7


In [82]:
import joblib
import numpy as np
from sklearn.feature_extraction.text import TfidfTransformer

In [83]:
model = joblib.load("/content/ML_7/spam_ham_model.pkl")
vectorizer = joblib.load("/content/ML_7/spam_ham_vectorizer.pkl")

In [84]:
input_text = ["Announcement Lottery"]
input_features = vectorizer.transform(input_text)
prediction = model.predict(input_features)
print("Prediction:", prediction[0])

Prediction: 1


In [85]:
input_text = ["Hi komal ji"]
input_features = vectorizer.transform(input_text)
prediction = model.predict(input_features)
print("Prediction:", prediction[0])

Prediction: 0
